#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person #test1  需要换数据库
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

#
resources:
static-locations: classpath:/templates/,classpath:/static/
#配置mybatis
mybatis:
mapper-locations: mapping/*.xml
type-aliases-package: com.aaa.house.entity

# 日志
logging:
  level:
    com:
      aaa:
        house:
          dao: debug
