#配置端口号和上下文路径
server:
  port: 8080


#配置数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.11.133:3306/hellohouse
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 945787475

  #关闭模板的缓存
  thymeleaf:
    cache: false
  #允许重启
  devtools:
    remote:
      restart:
        enabled: true
  #时区格式
  jackson:
    date-format: yyyy-MM-dd
  #访问路径
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB

# 配置mybatis
mybatis:
  mapper-locations: mapping/*.xml
  type-aliases-package: com.aaa.house.entity


# 日志打印
logging:
  level:
    com:
      aaa:
        house:
          dao: debug